spring.application.name=backend
server.port=4040

spring.datasource.url=jdbc:mysql://mysql-7896217-kachamsanthoshini-6acf.l.aivencloud.com:25727/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true