spring.application.name=backend
server.port=4040

spring.datasource.url=jdbc:mysql://mysql-118c9ecf-anurag-19e7.e.aivencloud.com:11312/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true